# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Build and Archive

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Build package
        run: mvn clean package -DskipTests=true

      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: JAR-Artifact
          path: target/*.jar

      - name: Unit testing
        run: mvn test

      - run: mvn clean test jacoco:report

      - name: Jacoco code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Upload Jacoco code coverage report
          path: target/site/jacoco

      - name: Set Build Version
        id: set_build_version
        run: echo "::set-output name=BUILD_VERSION::$(git rev-parse --short HEAD)-${{ github.run_number }}"

      - name: Build docker image
        run: docker build -t guruprasanna30/numeric-app:${{ steps.set_build_version.outputs.BUILD_VERSION }} .

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to docker hub
        run: docker push guruprasanna30/numeric-app:${{  steps.set_build_version.outputs.BUILD_VERSION }}
