# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Build and Archive

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - run: mvn clean package -DskipTests=true

      - name: Archive JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifacts
          path: target/*.jar

      - name: Build docker image
        run: |
          echo "GIT commit:  $GIT_COMMIT"
          echo "build version: $SHORT_COMMIT_SHA"
        run: docker build -t guruprasanna30/numeric-app:$GIT_COMMIT .

      - name: Push Docker image to docker hub
        run: docker push guruprasanna30/numeric-app:$GIT_COMMIT
