name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Build Version
        id: set_build_version
        run: echo "::set-output name=BUILD_VERSION::$(git rev-parse --short HEAD)-${{ github.run_number }}"

      - name: Display Build Version
        run: |
          echo "Build Version: ${{ steps.set_build_version.outputs.BUILD_VERSION }}"
